#!url=https://example.invalid/redacted
#!name=Billboard Ranking
#!desc=美国公告牌面板。将想要显示的条目数量填入songCount=，想要的榜单类型（有四种类型：billboard-200，billboard-artist-100，billboard-global-200，billboard-hot-100）填入sort=。例：songCount=10&sort=billboard-artist-100。不填默认展示前5条billboard-hot-100
#!homepage=https://yfamilys.com

[Script]
Billboard公告牌=type=cron,script-path=https://raw.githubusercontent.com/deezertidal/private/main/bb100.js,cronexp="0 0 12 ? * WED",wake-system=1,argument=songCount=&sort=