[General]
#!include ᴄʜʀᴏᴍᴀᴋᴏᴘɪᴀ.conf

[Ponte]
server-proxy-name= ꜱɴᴇʟʟ



[Proxy Group]
#!include ᴄʜʀᴏᴍᴀᴋᴏᴘɪᴀ.conf

[Rule]
#!include ᴄʜʀᴏᴍᴀᴋᴏᴘɪᴀ.conf

[Host]
#!include ᴄʜʀᴏᴍᴀᴋᴏᴘɪᴀ.conf

[MITM]
#!include ᴄʜʀᴏᴍᴀᴋᴏᴘɪᴀ.conf
